// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmwfTWoLqxWmha2qcI69i5vZ1lY6y6-o',
    appId: '1:1077461370490:web:a100b1b7f667b7b36addc3',
    messagingSenderId: '1077461370490',
    projectId: 'newflutterapp-d9525',
    authDomain: 'newflutterapp-d9525.firebaseapp.com',
    storageBucket: 'newflutterapp-d9525.appspot.com',
    measurementId: 'G-J93X2FQSP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQWiDhGXdHpHRdZBKbBSVm1qz-3-m3Y4',
    appId: '1:1077461370490:android:2145d9c83e570c806addc3',
    messagingSenderId: '1077461370490',
    projectId: 'newflutterapp-d9525',
    storageBucket: 'newflutterapp-d9525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_AQ_4W0IuL0ds7eCF7I5XiQ0R3sPrCGg',
    appId: '1:1077461370490:ios:f456c9e479df36996addc3',
    messagingSenderId: '1077461370490',
    projectId: 'newflutterapp-d9525',
    storageBucket: 'newflutterapp-d9525.appspot.com',
    iosBundleId: 'com.example.newflutter',
  );
}
